[env]
AXUM_HTTP_REQUESTS_TOTAL = "terrashine_http_requests_total"
AXUM_HTTP_REQUESTS_DURATION_SECONDS = "terrashine_http_requests_duration_seconds"
AXUM_HTTP_REQUESTS_PENDING = "terrashine_http_requests_pending"
